name: tf215
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - tensorflow[and-cuda]==2.15.0.post1
      - jupyterlab==4.0.12
      - numpy==1.26.4
      - matplotlib==3.7.5
      - scikit-learn==1.3.2
      - seaborn==0.13.2
